owner: Okkido
repo: status

sites:
  - name: Antonius
    url: https://www.antonius.me
  - name: Phonetic
    url: https://phonetic.xyz
  - name: Church of Procrastination
    url: https://churchofprocrastination.com
  - name: Världens bästa chili
    url: https://varldensbastachili.se

status-website:
  baseUrl: /status # where "repo" is your repository name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: ""
  introMessage: 
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
